[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/saschagrunert/nix?rev=43e48dfde7f9bcbf2052bbdf2fc0d6f276761557"]
git = "https://github.com/saschagrunert/nix"
rev = "43e48dfde7f9bcbf2052bbdf2fc0d6f276761557"
replace-with = "vendored-sources"

[source."git+https://github.com/saschagrunert/time?rev=22f9ac760e36ca965a7205056f719d5db8d153c1"]
git = "https://github.com/saschagrunert/time"
rev = "22f9ac760e36ca965a7205056f719d5db8d153c1"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = ".cargo-vendor"
