name: Create Release

on:
  push:
    tags:
      - "*"

env:
  CARGO_TERM_COLOR: always
  GO_VERSION: '1.23'
  ACTION_MSRV_TOOLCHAIN: 1.66.1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@6871f53176ad61624f978536bbf089c574dc19a2 # v8.0.1
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Setup Cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: .github/install-deps
      - name: Select Toolchain
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
        with:
          toolchain: ${{ env['ACTION_MSRV_TOOLCHAIN'] }}
          default: true
          override: true
          components: rustfmt
      - name: Build
        run: cargo build
      - name: Create Release Packaging
        run: make create-release-packages
        env:
          CI_TAG: ${{ steps.branch-name.outputs.tag }}
      - name: Release
        uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191 # v2.0.8
        with:
          files: "*.tar.gz"
